### PR TITLE
add meta description to mdx files

### PR DESCRIPTION
**Pull request by borft**
Basically, this looks for the first paragraph (p) in the body (inside <main />), and takes the text from it, limited to 500 chars, and sets that in the head/meta tags for docusaurus to use.

### CODE REVIEW

**Comment by jansentom** [comment]
Looks okay to me, but shouldn't we want to take complete sentences, or at least complete words?

**Review by jansentom — COMMENTED** [review]
LGTM, one generic comment.

**Review by jansentom — APPROVED** [review]
LGTM, one comment, posted twice ;)

**Comment by borft** [comment]
> Looks okay to me, but shouldn't we want to take complete sentences, or at least complete words?

Fair point. Now using whole words as a quick fix.

**Pull request merged**
