### PR TITLE
use instance_dtype instead of dtype

### PR DESCRIPTION
**Pull request by KathiaBarahona**
Currently failing when dataframe has a StructureDType series

### CODE REVIEW

**Review by thijs-obj — APPROVED** [review]
nice fix :+1:

**Comment by ivarpruijn** [comment]
Should we have a new release for this?

**Comment by KathiaBarahona** [comment]
> Should we have a new release for this?
yup, not high priority but we should

**Comment by jansentom** [comment]
I'll roll a new release for this EOD

**Pull request merged**
